version: '2'
services:
  myhero-ui:
    build: .
    image: juliocisco/myhero-ui
    ports:
     - "15080:80"
    environment:
     - myhero_app_server=${MYHERO_APP_SERVER}
     - myhero_spark_server=${MYHERO_SPARK_SERVER}
     - myhero_app_key=${MYHERO_APP_KEY}
networks:
  default:
     external:
       name: myhero_data_default
