---
apiVersion: v1
kind: Service
metadata:
  name: myhero-ui
  labels:
    app: myhero
    tier: ui
spec:
  ports:
  - port: 80
    name: http
    targetPort: 80
  selector:
    app: myhero
    tier: ui
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myhero-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myhero
      tier: ui
  template:
    metadata:
      labels:
        app: myhero
        tier: ui
    spec:
      containers:
      - name: myhero-ui
#        image: juliocisco/myhero-ui:latest
        image: {{.image}}
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        env:
          - name: myhero_spark_server
            value: http://spark-julio.ddns.net
          - name: myhero_app_server
            value: http://app-julio.ddns.net
          - name: myhero_app_key
            value: SecureApp
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 100m
            memory: 48M
      restartPolicy: Always
